apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: build-and-deploy-dev-1
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  params:
    - name: gitUrl
      value: https://github.com/bilalislam/gitops-using-argo-cd-and-tekton
    - name: gitRevision
      value: dev
    - name: imageUrl
      value: ninjafx/gitops-using-argo-cd-and-tekton
    - name: serviceName
      value: server
    - name: filePath
      value: clusters/server/dev/server-deploy.yaml
    - name: yamlField
      value: .spec.template.spec.containers[0].image
  pipelineRef:
    name: build-and-deploy-pipeline
  resources:
  - name: source-repo
    resourceSpec:
      type: git
      params:
      - name: revision
        value: dev
      - name: url
        value: https://github.com/bilalislam/gitops-using-argo-cd-and-tekton
  - name: gitops-service
    resourceSpec:
      type: image
      params:
      - name: url
        value: ninjafx/gitops-using-argo-cd-and-tekton:dev
  serviceAccountName: pipeline-account
  workspaces:
    - name: git-source
      persistentVolumeClaim:
        claimName: git-source-pvc

