apiVersion: v1
kind: Secret
metadata:
  name: github-secret
  annotations:
    tekton.dev/git-0: https://github.com
type: kubernetes.io/basic-auth
stringData:
  username: bilalislam
  password: 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