apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - argocd-ns.yaml
  #- github.com/argoproj/argo-cd/manifests/cluster-install/?ref=v1.7.8
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.4.0-rc4/manifests/install.yaml
  - argocd-ing.yaml
  - argocd-metrics-sm.yaml
  - argocd-repo-server-metrics-sm.yaml
  - argocd-server-metrics-sm.yaml
